### PR TITLE
Remove Travis JWT plugin

### PR DESCRIPTION
**Pull request by ryantmer**
As per https://blog.travis-ci.com/2018-01-23-jwt-addon-is-deprecated, the JWT plugin is being deprecated. Instead, use an encrypted SAUCE_ACCESS_KEY.

### CODE REVIEW

**Comment by dbatiste** [comment]
Or should we be doing it this way?

https://github.com/BrightspaceUI/datetime-picker/pull/41/files

**Comment by ryantmer** [comment]
Ah yeah, good call. Forgot that this wouldn't work with forks, I'll update things.

**Comment by ryantmer** [comment]
Oh hmm, although that would mean we don't run Sauce at all when something comes from a fork, correct? (I guess it's better than everything blowing up for forks, granted.)

**Comment by dbatiste** [comment]
Yeah.  For most of our contributors we can get away with branching in the repo instead of fork.  I know that's not how everyone works though... and I know there are reasons to work that way.  ;)

**Comment by dlockhart** [comment]
Exactly yeah. Better than nothing? Forks are the only way someone without write access to these repos could contribute, so I like supporting that workflow even if it's not perfect.

**Pull request merged**
